# Generated by Django 3.0.5 on 2020-04-08 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
