# Generated by Django 3.0.5 on 2020-04-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200408_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
