# Generated by Django 3.0.5 on 2020-04-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_chapter_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.Chapter'),
        ),
    ]
