# Generated by Django 3.0.5 on 2020-04-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200408_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='thumbnail',
            new_name='cover',
        ),
    ]
