# Generated by Django 3.0.5 on 2020-04-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200408_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='cover',
            new_name='thumbnail',
        ),
    ]
